In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot') #Style sheet

In [5]:
# Load datasets
cash = pd.read_csv('https://raw.githubusercontent.com/kurtisjw/project-1-ironhack-payments-es/main/project_dataset/extract%20-%20cash%20request%20-%20data%20analyst.csv')
fees = pd.read_csv('https://raw.githubusercontent.com/kurtisjw/project-1-ironhack-payments-es/main/project_dataset/extract%20-%20fees%20-%20data%20analyst%20-%20.csv')

In [6]:
cash.head(5)

,id,amount,status,created_at,updated_at,user_id,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,money_back_date,transfer_type,send_at,recovery_status,reco_creation,reco_last_update
0,5,100.0,rejected,2019-12-10 19:05:21.596873+00,2019-12-11 16:47:42.40783+00,804.0,2019-12-11 16:47:42.405646+00,NaN,2020-01-09 19:05:21.596363+00,NaN,NaN,regular,NaN,NaN,NaN,NaN
1,70,100.0,rejected,2019-12-10 19:50:12.34778+00,2019-12-11 14:24:22.900054+00,231.0,2019-12-11 14:24:22.897988+00,NaN,2020-01-09 19:50:12.34778+00,NaN,NaN,regular,NaN,NaN,NaN,NaN
2,7,100.0,rejected,2019-12-10 19:13:35.82546+00,2019-12-11 09:46:59.779773+00,191.0,2019-12-11 09:46:59.777728+00,NaN,2020-01-09 19:13:35.825041+00,NaN,NaN,regular,NaN,NaN,NaN,NaN
3,10,99.0,rejected,2019-12-10 19:16:10.880172+00,2019-12-18 14:26:18.136163+00,761.0,2019-12-18 14:26:18.128407+00,NaN,2020-01-09 19:16:10.879606+00,NaN,NaN,regular,NaN,NaN,NaN,NaN
4,1594,100.0,rejected,2020-05-06 09:59:38.877376+00,2020-05-07 09:21:55.34008+00,7686.0,2020-05-07 09:21:55.320193+00,NaN,2020-06-05 22:00:00+00,NaN,NaN,regular,NaN,NaN,NaN,NaN

In [161]:
fees.head(5)

,id,cash_request_id,type,status,category,total_amount,reason,created_at,updated_at,paid_at,from_date,to_date,charge_moment
0,6537,14941.0,instant_payment,rejected,NaN,5.0,Instant Payment Cash Request 14941,2020-09-07 10:47:27.42315+00,2020-10-13 14:25:09.396112+00,2020-12-17 14:50:07.47011+00,NaN,NaN,after
1,6961,11714.0,incident,accepted,rejected_direct_debit,5.0,rejected direct debit,2020-09-09 20:51:17.998653+00,2020-10-13 14:25:15.537063+00,2020-12-08 17:13:10.45908+00,NaN,NaN,after
2,16296,23371.0,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 23371,2020-10-23 10:10:58.352972+00,2020-10-23 10:10:58.352994+00,2020-11-04 19:34:37.43291+00,NaN,NaN,after
3,20775,26772.0,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 26772,2020-10-31 15:46:53.643958+00,2020-10-31 15:46:53.643982+00,2020-11-19 05:09:22.500223+00,NaN,NaN,after
4,11242,19350.0,instant_payment,accepted,NaN,5.0,Instant Payment Cash Request 19350,2020-10-06 08:20:17.170432+00,2020-10-13 14:25:03.267983+00,2020-11-02 14:45:20.355598+00,NaN,NaN,after

In [162]:
# Display number of rows and columns in cash dataframe
cash.shape

(23970, 16)

In [163]:
# Display number of rows and columns in fees dataframe
fees.shape

(21061, 13)

In [164]:
# List columns in cash dataframe
cash.columns

Index(['id', 'amount', 'status', 'created_at', 'updated_at', 'user_id',
       'moderated_at', 'deleted_account_id', 'reimbursement_date',
       'cash_request_received_date', 'money_back_date', 'transfer_type',
       'send_at', 'recovery_status', 'reco_creation', 'reco_last_update'],
      dtype='object')

In [13]:
# List columns in fees dataframe
fees.columns

Index(['id', 'cash_request_id', 'type', 'status', 'category', 'total_amount',
       'reason', 'created_at', 'updated_at', 'paid_at', 'from_date', 'to_date',
       'charge_moment'],
      dtype='object')

In [166]:
# Show information about cash dataframe
cash.describe()

                 id        amount        user_id  deleted_account_id
count  23970.000000  23970.000000   21867.000000         2104.000000
mean   13910.966124     82.720818   32581.250789         9658.755228
std     7788.117214     26.528065   27618.565773         7972.743249
min        3.000000      1.000000      34.000000           91.000000
25%     7427.250000     50.000000   10804.000000         3767.000000
50%    14270.500000    100.000000   23773.000000         6121.500000
75%    20607.750000    100.000000   46965.000000        16345.000000
max    27010.000000    200.000000  103719.000000        30445.000000

In [167]:
# Show information about fees dataframe
fees.describe()

                 id  cash_request_id  total_amount
count  21061.000000     21057.000000  21061.000000
mean   10645.355111     16318.449162      5.000237
std     6099.315256      6656.149949      0.034453
min        1.000000      1456.000000      5.000000
25%     5385.000000     11745.000000      5.000000
50%    10652.000000     17160.000000      5.000000
75%    15925.000000     21796.000000      5.000000
max    21193.000000     27010.000000     10.000000

## Data Types

In [168]:
# Show data type of each column in cash dataframe
cash.dtypes

id                              int64
amount                        float64
status                         object
created_at                     object
updated_at                     object
user_id                       float64
moderated_at                   object
deleted_account_id            float64
reimbursement_date             object
cash_request_received_date     object
money_back_date                object
transfer_type                  object
send_at                        object
recovery_status                object
reco_creation                  object
reco_last_update               object
dtype: object

In [169]:
# Show data type of each column in fees dataframe
fees.dtypes

id                   int64
cash_request_id    float64
type                object
status              object
category            object
total_amount       float64
reason              object
created_at          object
updated_at          object
paid_at             object
from_date           object
to_date             object
charge_moment       object
dtype: object

In [170]:
# Convert 'created_at' data type to to datetime
cash['created_at'] = pd.to_datetime(cash['created_at'])

In [7]:
# Convert all date/time columns in cash dataframe to datetime data type -

date_time_columns = ['created_at', 'updated_at',
       'moderated_at','reimbursement_date',
       'cash_request_received_date', 'money_back_date',
       'send_at', 'reco_creation', 'reco_last_update']

cash[date_time_columns] = cash[date_time_columns].apply(pd.to_datetime, errors = 'coerce')

cash.dtypes

id                                          int64
amount                                    float64
status                                     object
created_at                    datetime64[ns, UTC]
updated_at                    datetime64[ns, UTC]
user_id                                   float64
moderated_at                  datetime64[ns, UTC]
deleted_account_id                        float64
reimbursement_date            datetime64[ns, UTC]
cash_request_received_date         datetime64[ns]
money_back_date               datetime64[ns, UTC]
transfer_type                              object
send_at                       datetime64[ns, UTC]
recovery_status                            object
reco_creation                 datetime64[ns, UTC]
reco_last_update              datetime64[ns, UTC]
dtype: object

In [16]:
# Convert status column to category data type. Converting text data with a
# limited number of unique values to the category type can significantly reduce
# memory usage.
cash['status'] = cash['status'].astype('category')

# Get the different categories present in the status column
status_categories = cash['status'].cat.categories

for category in status_categories:
    print(category)

active
canceled
direct_debit_rejected
direct_debit_sent
money_back
rejected
transaction_declined

In [172]:
# Create subset of columns by commenting out columns that we don't want to use right now

cash_subset = cash[['id', 'amount', 'status', 'created_at', 'updated_at', 'user_id',
       # 'moderated_at', 'deleted_account_id', 'reimbursement_date',
       # 'cash_request_received_date', 'money_back_date', 'transfer_type',
       'send_at', 'recovery_status', 'reco_creation', 'reco_last_update']].copy()

cash_subset.head(5)

,id,amount,status,created_at,updated_at,user_id,send_at,recovery_status,reco_creation,reco_last_update
0,5,100.0,rejected,2019-12-10 19:05:21.596873+00:00,2019-12-11 16:47:42.407830+00:00,804.0,NaT,NaN,NaT,NaT
1,70,100.0,rejected,2019-12-10 19:50:12.347780+00:00,2019-12-11 14:24:22.900054+00:00,231.0,NaT,NaN,NaT,NaT
2,7,100.0,rejected,2019-12-10 19:13:35.825460+00:00,2019-12-11 09:46:59.779773+00:00,191.0,NaT,NaN,NaT,NaT
3,10,99.0,rejected,2019-12-10 19:16:10.880172+00:00,2019-12-18 14:26:18.136163+00:00,761.0,NaT,NaN,NaT,NaT
4,1594,100.0,rejected,2020-05-06 09:59:38.877376+00:00,2020-05-07 09:21:55.340080+00:00,7686.0,NaT,NaN,NaT,NaT

In [173]:
# Check for duplicate rows in dataframe - none found
cash.loc[cash.duplicated()]

Empty DataFrame
Columns: [id, amount, status, created_at, updated_at, user_id, moderated_at, deleted_account_id, reimbursement_date, cash_request_received_date, money_back_date, transfer_type, send_at, recovery_status, reco_creation, reco_last_update]
Index: []

In [11]:
#Check for duplicated user_id

cash.loc[cash.duplicated(subset = ['user_id'])]

,id,amount,status,created_at,updated_at,user_id,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,money_back_date,transfer_type,send_at,recovery_status,reco_creation,reco_last_update
8,5672,100.0,canceled,2020-06-28 12:06:33.712840+00:00,2020-06-28 12:06:33.712853+00:00,NaN,NaT,2499.0,NaT,NaT,NaT,regular,NaT,NaN,NaT,NaT
19,545,100.0,rejected,2020-01-29 13:53:03.343598+00:00,2020-02-08 06:21:16.156719+00:00,NaN,2020-01-29 14:39:11.563872+00:00,304.0,2020-02-28 13:53:03.343216+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT
21,613,100.0,rejected,2020-02-05 17:37:56.852948+00:00,2020-02-08 06:21:16.152290+00:00,NaN,2020-02-06 12:48:09.880702+00:00,304.0,2020-03-08 17:37:56.842421+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT
25,84,100.0,rejected,2019-12-11 07:30:42.567035+00:00,2020-01-10 16:58:06.837117+00:00,NaN,2020-01-10 16:58:06.830329+00:00,91.0,2020-01-10 07:30:42.567035+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT
34,956,99.0,rejected,2020-03-19 16:56:44.663085+00:00,2020-03-30 19:45:33.537732+00:00,NaN,2020-03-20 13:50:09.323560+00:00,575.0,2020-04-18 16:56:44.662679+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23960,26969,50.0,direct_debit_sent,2020-11-01 17:31:03.345533+00:00,2021-01-06 09:07:31.575691+00:00,3377.0,NaT,NaN,NaT,2020-11-02,NaT,instant,2020-11-01 17:31:25.526137+00:00,NaN,NaT,NaT
23964,16834,100.0,money_back,2020-09-19 07:37:14.351567+00:00,2021-02-05 12:11:58.186458+00:00,20064.0,2020-09-19 15:37:54.670099+00:00,NaN,NaT,2020-09-22,2021-02-05 12:11:58.131036+00:00,instant,2020-09-26 07:37:14.299162+00:00,completed,2020-10-15 22:27:12.949488+00:00,2021-02-05 12:11:58.134306+00:00
23965,20616,100.0,money_back,2020-10-12 13:54:11.686225+00:00,2021-02-06 20:17:49.292493+00:00,13681.0,NaT,NaN,NaT,2020-10-13,2021-02-06 20:17:49.257521+00:00,instant,2020-10-12 13:54:24.352856+00:00,NaN,NaT,NaT
23966,25243,50.0,money_back,2020-10-27 14:41:25.734910+00:00,2020-12-18 13:15:40.843946+00:00,NaN,NaT,30367.0,NaT,2020-10-28,2020-12-01 13:26:53.787672+00:00,instant,2020-10-27 14:41:57.901946+00:00,completed,2020-11-12 23:20:41.928788+00:00,2020-12-01 13:26:53.815504+00:00
23969,19886,100.0,direct_debit_sent,2020-10-08 14:16:52.155661+00:00,2021-01-05 15:45:52.645536+00:00,44867.0,NaT,NaN,NaT,2020-10-10,NaT,instant,2020-10-08 14:17:04.526139+00:00,NaN,NaT,NaT

In [175]:
#Check for duplicated id - none found

cash.loc[cash.duplicated(subset = ['id'])]

Empty DataFrame
Columns: [id, amount, status, created_at, updated_at, user_id, moderated_at, deleted_account_id, reimbursement_date, cash_request_received_date, money_back_date, transfer_type, send_at, recovery_status, reco_creation, reco_last_update]
Index: []

In [176]:
# Check unique values of money_back_date column as there is no information in the lexique

unique_values_money_back_date = cash['money_back_date'].unique()
unique_values_money_back_date

<DatetimeArray>
[                             'NaT', '2020-07-06 03:36:03.023521+00:00',
 '2020-06-03 05:11:35.312616+00:00', '2020-06-13 06:36:34.188042+00:00',
 '2020-06-10 08:20:10.398977+00:00', '2020-11-06 07:16:21.845479+00:00',
 '2020-04-14 20:25:28.747087+00:00', '2020-03-31 20:00:52.443628+00:00',
 '2020-09-18 07:45:25.740402+00:00', '2020-06-27 03:28:09.137532+00:00',
 ...
 '2021-02-05 21:25:44.230776+00:00', '2021-02-05 20:28:11.583499+00:00',
 '2021-02-06 20:16:09.463799+00:00', '2021-02-05 20:48:23.237207+00:00',
 '2021-02-05 12:04:06.144421+00:00', '2021-02-05 12:11:58.131036+00:00',
 '2021-02-06 20:17:49.257521+00:00', '2020-12-01 13:26:53.787672+00:00',
 '2021-02-05 12:19:30.626289+00:00', '2021-02-05 13:14:19.689906+00:00']
Length: 12041, dtype: datetime64[ns, UTC]

In [177]:
# Count total values in money_back_date column. This does not include NaN (Not a Number) entries
count_values_money_back_date = cash['money_back_date'].count()
count_values_money_back_date

12040

In [178]:
# Set 'created_at' column as index
cash_copy = cash.copy()
cash_copy.set_index('created_at', inplace=True)

# Group by month and count the number of operations per month. 'M' stands for month end frequency. Other options include W, D, Q, Y (week, day, quarter,)
operations_by_month = cash_copy.resample('M').size()

print(operations_by_month)

# The output shows the last date of each month. In pandas, when you use the
# resample() function to group data by time periods like months, weeks, etc.,
# the default behavior is to label the groups with the end timestamp of each
# period.

created_at
2019-11-30 00:00:00+00:00       1
2019-12-31 00:00:00+00:00     289
2020-01-31 00:00:00+00:00     223
2020-02-29 00:00:00+00:00     184
2020-03-31 00:00:00+00:00     244
2020-04-30 00:00:00+00:00     473
2020-05-31 00:00:00+00:00     837
2020-06-30 00:00:00+00:00    2615
2020-07-31 00:00:00+00:00    3601
2020-08-31 00:00:00+00:00    3417
2020-09-30 00:00:00+00:00    4221
2020-10-31 00:00:00+00:00    7725
2020-11-30 00:00:00+00:00     140
Freq: M, dtype: int64

In [179]:
#Count number of occurrences of each user_id in the cash dataframe. Displayed in descending order.

user_id_counts = cash['user_id'].value_counts()
user_id_counts

user_id
3377.0     19
2142.0     18
13851.0    18
2530.0     17
1159.0     17
           ..
4938.0      1
79289.0     1
74036.0     1
57112.0     1
64517.0     1
Name: count, Length: 10798, dtype: int64

In [180]:
# Count total number of unique user IDs in the dataframe (see also 'length' of previous ouput)
unique_user_ids = cash['user_id'].nunique()
unique_user_ids

10798

In [187]:
# Create month and cohorts columns
cash.sort_values(by='user_id', inplace=True)
cash['month'] = cash['created_at'].dt.to_period('M')
cash['cohorts'] = cash.groupby('user_id')['month'].transform('min')
cash[['cohorts', 'month', 'user_id']].head(10)

<ipython-input-187-06b822c40eeb>:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  cash['month'] = cash['created_at'].dt.to_period('M')

       cohorts    month  user_id
538    2020-04  2020-04     34.0
91     2019-12  2020-02     35.0
345    2019-12  2020-01     35.0
5298   2019-12  2020-08     35.0
58     2019-12  2019-12     35.0
180    2019-12  2019-12     35.0
6842   2019-12  2020-09     35.0
670    2019-12  2020-03     35.0
22010  2019-11  2020-10     47.0
32     2019-11  2019-12     47.0

In [188]:
# Check for missing values in cash dataframe
print(cash.isnull().sum())

id                                0
amount                            0
status                            0
created_at                        0
updated_at                        0
user_id                        2103
moderated_at                   8058
deleted_account_id            21866
reimbursement_date            20920
cash_request_received_date     7681
money_back_date               11930
transfer_type                     0
send_at                        7504
recovery_status               20640
reco_creation                 20640
reco_last_update              20640
month                             0
cohorts                        2103
dtype: int64

In [194]:
# Because the user_id and cohorts columns have 2103 missing values, we want to investigate further
missing_user_id = cash[cash['user_id'].isnull()]
missing_user_id.head(1000)

,id,amount,status,created_at,updated_at,user_id,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,money_back_date,transfer_type,send_at,recovery_status,reco_creation,reco_last_update,month,cohorts
7,654,100.0,rejected,2020-02-10 01:11:53.808270+00:00,2020-02-10 11:53:32.104131+00:00,NaN,2020-02-10 09:11:21.350695+00:00,309.0,2020-03-11 01:11:53.807930+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT,2020-02,NaT
8,5672,100.0,canceled,2020-06-28 12:06:33.712840+00:00,2020-06-28 12:06:33.712853+00:00,NaN,NaT,2499.0,NaT,NaT,NaT,regular,NaT,NaN,NaT,NaT,2020-06,NaT
19,545,100.0,rejected,2020-01-29 13:53:03.343598+00:00,2020-02-08 06:21:16.156719+00:00,NaN,2020-01-29 14:39:11.563872+00:00,304.0,2020-02-28 13:53:03.343216+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT,2020-01,NaT
21,613,100.0,rejected,2020-02-05 17:37:56.852948+00:00,2020-02-08 06:21:16.152290+00:00,NaN,2020-02-06 12:48:09.880702+00:00,304.0,2020-03-08 17:37:56.842421+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT,2020-02,NaT
25,84,100.0,rejected,2019-12-11 07:30:42.567035+00:00,2020-01-10 16:58:06.837117+00:00,NaN,2020-01-10 16:58:06.830329+00:00,91.0,2020-01-10 07:30:42.567035+00:00,NaT,NaT,regular,NaT,NaN,NaT,NaT,2019-12,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6706,11777,100.0,rejected,2020-08-10 16:57:27.936787+00:00,2020-08-11 09:05:17.904447+00:00,NaN,2020-08-11 09:05:17.901836+00:00,6334.0,2020-08-24 04:57:36.273000+00:00,NaT,NaT,instant,2020-08-17 16:57:27.936373+00:00,NaN,NaT,NaT,2020-08,NaT
6707,11910,100.0,rejected,2020-08-11 09:29:25.121902+00:00,2020-08-11 09:43:58.710107+00:00,NaN,2020-08-11 09:43:58.707145+00:00,6334.0,2020-08-25 09:29:46.196000+00:00,NaT,NaT,regular,2020-08-18 09:29:25.121486+00:00,NaN,NaT,NaT,2020-08,NaT
6708,11931,100.0,rejected,2020-08-11 10:22:21.001039+00:00,2020-08-11 10:30:10.695923+00:00,NaN,2020-08-11 10:30:10.693197+00:00,6334.0,2020-08-25 10:22:29.530000+00:00,NaT,NaT,regular,2020-08-18 10:22:21.000660+00:00,NaN,NaT,NaT,2020-08,NaT
6709,11947,100.0,rejected,2020-08-11 11:24:28.822363+00:00,2020-08-11 15:12:01.626289+00:00,NaN,2020-08-11 15:12:01.623551+00:00,6334.0,2020-08-24 23:24:37.298000+00:00,NaT,NaT,regular,2020-08-18 11:24:28.821677+00:00,NaN,NaT,NaT,2020-08,NaT
6724,16668,50.0,rejected,2020-09-17 17:48:36.760318+00:00,2020-09-18 07:44:56.089029+00:00,NaN,2020-09-18 07:44:56.080631+00:00,5610.0,NaT,NaT,NaT,instant,2020-09-24 17:48:36.699207+00:00,NaN,NaT,NaT,2020-09,NaT

In [183]:
cash['user_id'].count()

21867

In [192]:
cash['cohorts'].count()

21867

In [231]:
cash['deleted_account_id'].count()
# In the lexique it explains "If a user delete his account, we are replacing the
# user_id by this id. It corresponds to a unique ID in the deleted account
# table..."

# If we subtract the number of missing user_ids (2103) from the total number of
# rows in the dataframe (23970), we get the number 21866, which is the same
# number of missing deleted_account_ids in the dataframe. We can also see that
# the deleted_account_id column contains 2104 values, almost the same number as
# missing user_ids. Therefore, we can conclude that the 2103 missing user_ids
# have been replaced by deleted_account_ids after the user deleted their
# account. %% Filter rows where the 'user_id' value is the same as the
# 'deleted_account_id' value - none found

2104

In [212]:
# Filter rows where the 'user_id' value is the same as the 'deleted_account_id' value - none found
common_values = cash[cash['user_id'] == cash['deleted_account_id']]
common_values

Empty DataFrame
Columns: [id, amount, status, created_at, updated_at, user_id, moderated_at, deleted_account_id, reimbursement_date, cash_request_received_date, money_back_date, transfer_type, send_at, recovery_status, reco_creation, reco_last_update, month, cohorts]
Index: []

In [196]:
# Check if the user_id and cohorts columns are equal. If the columns contain the
# same values but not in the same order, it will return false.
cash['user_id'].equals(cash['cohorts'])

False

In [197]:
# Check for missing values in fees dataframe
print(fees.isnull().sum())

id                     0
cash_request_id        4
type                   0
status                 0
category           18865
total_amount           0
reason                 0
created_at             0
updated_at             0
paid_at             5530
from_date          13295
to_date            13295
charge_moment          0
dtype: int64

In [213]:
# Find shared column names in the cash and fees dataframes
common_columns = set(cash.columns).intersection(set(fees.columns))
print(common_columns)

{'updated_at', 'id', 'status', 'created_at'}

In [214]:
# Left and right merges of the cash and fees dataframes
merged_df_left = pd.merge(cash, fees, on = 'id', how = 'left')
merged_df_right = pd.merge(cash, fees, on = 'id', how = 'right')

In [229]:
merged_df_left.head(5)

,id,amount,status_x,created_at_x,updated_at_x,user_id,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,...,status_y,category,total_amount,reason,created_at_y,updated_at_y,paid_at,from_date,to_date,charge_moment
0,1302,100.0,rejected,2020-04-20 15:50:21.187257+00:00,2020-04-22 12:03:34.439811+00:00,34.0,2020-04-22 12:03:34.434712+00:00,NaN,2020-04-27 15:50:21.186890+00:00,NaT,...,accepted,NaN,5.0,Postpone Cash Request 3910,2020-07-11 15:32:59.699714+00,2020-10-13 14:25:02.264802+00,2020-07-11 15:33:03.823783+00,2020-08-11 22:00:00+00,2020-09-10 22:00:00+00,before
1,758,90.0,rejected,2020-02-28 10:51:11.440880+00:00,2020-02-28 14:13:21.504350+00:00,35.0,2020-02-28 14:13:21.501335+00:00,NaN,NaT,NaT,...,cancelled,NaN,5.0,Postpone Cash Request 5085,2020-06-29 06:25:05.218692+00,2020-10-13 14:25:15.869267+00,NaN,2020-07-08 22:00:00+00,2020-07-19 06:25:00.679+00,after
2,510,90.0,rejected,2020-01-27 19:50:46.387431+00:00,2020-01-28 14:52:30.164273+00:00,35.0,2020-01-28 14:52:30.160427+00:00,NaN,2020-02-03 19:50:46.387008+00:00,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12794,100.0,rejected,2020-08-17 13:19:41.318905+00:00,2020-08-17 15:04:14.916382+00:00,35.0,2020-08-17 15:04:14.912309+00:00,NaN,NaT,NaT,...,accepted,NaN,5.0,Instant Payment Cash Request 19912,2020-10-12 07:47:50.212477+00,2020-10-13 14:25:18.791951+00,2020-10-27 05:00:50.489684+00,NaN,NaN,after
4,150,100.0,rejected,2019-12-13 20:27:38.106778+00:00,2019-12-18 15:20:41.722482+00:00,35.0,2019-12-18 15:20:41.715612+00:00,NaN,2019-12-20 20:27:38.106319+00:00,NaT,...,accepted,NaN,5.0,Postpone Cash Request 2590,2020-06-10 20:51:22.870023+00,2020-10-13 14:25:00.929233+00,NaN,2020-07-05 22:00:00+00,2020-07-20 22:00:00+00,before

In [228]:
merged_df_right.head(5)

,id,amount,status_x,created_at_x,updated_at_x,user_id,moderated_at,deleted_account_id,reimbursement_date,cash_request_received_date,...,status_y,category,total_amount,reason,created_at_y,updated_at_y,paid_at,from_date,to_date,charge_moment
0,6537,100.0,money_back,2020-07-04 05:59:49.246265+00:00,2020-12-18 13:09:59.300546+00:00,26978.0,2020-07-04 16:38:52.657547+00:00,NaN,NaT,2020-07-07,...,rejected,NaN,5.0,Instant Payment Cash Request 14941,2020-09-07 10:47:27.42315+00,2020-10-13 14:25:09.396112+00,2020-12-17 14:50:07.47011+00,NaN,NaN,after
1,6961,100.0,money_back,2020-07-07 17:45:03.352406+00:00,2020-12-18 13:10:14.466442+00:00,13539.0,2020-07-08 13:45:03.327043+00:00,NaN,NaT,2020-07-10,...,accepted,rejected_direct_debit,5.0,rejected direct debit,2020-09-09 20:51:17.998653+00,2020-10-13 14:25:15.537063+00,2020-12-08 17:13:10.45908+00,NaN,NaN,after
2,16296,50.0,money_back,2020-09-15 19:05:39.267562+00:00,2020-12-18 13:09:14.593043+00:00,13756.0,2020-09-16 07:53:30.307123+00:00,NaN,NaT,2020-09-17,...,accepted,NaN,5.0,Instant Payment Cash Request 23371,2020-10-23 10:10:58.352972+00,2020-10-23 10:10:58.352994+00,2020-11-04 19:34:37.43291+00,NaN,NaN,after
3,20775,100.0,money_back,2020-10-13 08:15:07.746660+00:00,2020-12-18 13:11:57.614945+00:00,61460.0,NaT,NaN,NaT,2020-10-14,...,accepted,NaN,5.0,Instant Payment Cash Request 26772,2020-10-31 15:46:53.643958+00,2020-10-31 15:46:53.643982+00,2020-11-19 05:09:22.500223+00,NaN,NaN,after
4,11242,50.0,money_back,2020-08-06 22:46:50.681779+00:00,2020-12-18 13:10:59.725981+00:00,31188.0,2020-08-07 10:02:38.990829+00:00,NaN,NaT,2020-08-12,...,accepted,NaN,5.0,Instant Payment Cash Request 19350,2020-10-06 08:20:17.170432+00,2020-10-13 14:25:03.267983+00,2020-11-02 14:45:20.355598+00,NaN,NaN,after

In [218]:
# Check for duplicated values in the id columns of the cash and fees dataframes - none found

print(cash['id'].duplicated().sum())
print(fees['id'].duplicated().sum())

0
0

In [222]:
# Check for duplicated values in the cash_request_id column of the fees dataframe
print(fees['cash_request_id'].duplicated().sum())

# Interestingly, there are a large number of duplicated cash_request_ids

8127

In [227]:
# Display duplicated cash_request_ids
duplicated_ids = fees[fees['cash_request_id'].duplicated()]
duplicated_ids.head(5)

,id,cash_request_id,type,status,category,total_amount,reason,created_at,updated_at,paid_at,from_date,to_date,charge_moment
132,21160,23676.0,postpone,cancelled,NaN,5.0,Postpone Cash Request 23676,2020-11-01 22:18:20.603622+00,2020-11-01 22:18:20.603646+00,NaN,2020-11-07 16:55:20.218+00,2020-11-13 11:00:00+00,before
157,20943,18606.0,postpone,cancelled,NaN,5.0,Postpone Cash Request 18606,2020-11-01 07:22:33.293219+00,2020-11-01 07:22:33.293241+00,NaN,2020-11-03 22:00:00+00,2020-11-28 11:00:00+00,before
160,21177,15272.0,postpone,cancelled,NaN,5.0,Postpone Cash Request 15272,2020-11-01 23:02:11.199619+00,2020-11-01 23:02:11.19965+00,NaN,2020-10-31 23:00:00+00,2020-11-30 23:00:00+00,before
191,21178,15272.0,postpone,cancelled,NaN,5.0,Postpone Cash Request 15272,2020-11-01 23:02:52.843985+00,2020-11-01 23:02:52.844008+00,NaN,2020-10-31 23:00:00+00,2020-11-30 23:00:00+00,before
193,20944,18606.0,postpone,accepted,NaN,5.0,Postpone Cash Request 18606,2020-11-01 07:24:10.312286+00,2020-11-01 07:24:14.449736+00,2020-11-01 07:24:14.588116+00,2020-11-03 22:00:00+00,2020-11-30 11:00:00+00,before

In [223]:
# Get the unique values in the 'reason' column for the duplicated rows
unique_reasons = duplicated_ids['reason'].unique()
unique_reasons

array(['Postpone Cash Request 23676', 'Postpone Cash Request 18606',
       'Postpone Cash Request 15272', ...,
       'Instant Payment Cash Request 10826',
       'Instant Payment Cash Request 23628',
       'Instant Payment Cash Request 20982'], dtype=object)

In [224]:
# Get the unique values in the 'status' column for the duplicated rows
unique_status = duplicated_ids['status'].unique()
unique_status

array(['cancelled', 'accepted', 'rejected', 'confirmed'], dtype=object)

In [225]:
# Get the unique values in the 'category' column for the duplicated rows
unique_category = duplicated_ids['category'].unique()
unique_category

array([nan, 'rejected_direct_debit', 'month_delay_on_payment'],
      dtype=object)

In [12]:
# I did not find a pattern or correlation between the
# duplicated user_ids and the values in the status/reason/category columns.